payload:
  # > Facebook
  - DOMAIN-SUFFIX,fb.com
  - DOMAIN-SUFFIX,fb.me
  - DOMAIN-KEYWORD,facebook
  - DOMAIN-KEYWORD,fbcdn
  
  # > Instagram
  - DOMAIN-KEYWORD,instagram
  - DOMAIN-SUFFIX,instagr.am

  # > Other
  - DOMAIN-SUFFIX,messenger.com
  - DOMAIN-SUFFIX,oculus.com
  - DOMAIN-SUFFIX,oculuscdn.com
